global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "rpc"
    static_configs:
      - targets: ["rpc:8000"]

  - job_name: "static-gateway"
    static_configs:
      - targets: ["static-gateway:8001"]

  - job_name: "upper"
    static_configs:
      - targets: ["upper:8000"]

  - job_name: "lower"
    static_configs:
      - targets: ["lower:8000"]
